#pragma once

#define MATRIX_ROWS 12
#define MATRIX_COLS 8

#define SPI_DRIVER SPID1
#define SPI_SCK_PIN A5
#define SPI_SCK_PAL_MODE 0
#define SPI_MOSI_PIN A7
#define SPI_MOSI_PAL_MODE 0
#define SPI_MISO_PIN A6
#define SPI_MISO_PAL_MODE 0

#define SN74X165_SPI_SLAVE_SELECT_PIN A4 // NSS
#define SN74X165_PL_PIN A3
#define SN74X165_LENGTH MATRIX_ROWS
#define SN74X165_SPI_MODE 0
#define SN74X165_SPI_LSBFIRST false
#define SN74X165_SPI_CLOCK_DIVISOR 64